name: ci-dotnet-workflow
on: 
  pull_request:
    branches: 
      - develop
jobs: 
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '5.0', '6.0' ]
    steps:
      - uses: actions/checkout
      - uses: actions/setup-dotnet
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build ContinuousIntegrationCourse
      - run: dotnet test ContinuousIntegrationCourseTests