name: ci-dotnet-workflow
on: 
  pull_request:
    branches: 
      - develop
jobs: 
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '5.0', '6.0' ]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build ContinuousIntegrationCourse
      - run: dotnet test ContinuousIntegrationCourseTests