name: ci-c#-workflow
on: 
  pull_request:
    branches: 
      - develop
jobs: 
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['5.0.x','6.0.x']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build ContinuousIntegrationCourse
      - run: dotnet test ContinuousIntegrationCourseTests